# Generated by Django 4.0.4 on 2025-02-06 06:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='recipient',
        ),
        migrations.AddField(
            model_name='feedback',
            name='recipient',
            field=models.ManyToManyField(related_name='received_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
