# Generated by Django 5.1 on 2025-02-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_alter_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='value',
        ),
    ]
